from . import act_accounting
from . import act_indenture
from . import account_move
from . import fee_group
from . import items_fee
from . import vat_gtgt
from . import act_account
from . import res_config
from . import res_currency
from . import res_partner
from . import account_synthetic
from . import detail_account_payment
from . import account_payment
from . import act_advance
from . import account_journal
